// Generated by scripts/generate-desktop-contracts.ts. Do not edit directly.



export interface EmptyRequest {}

export interface RunPreflightRequest {
    token?: string;
}

export interface SaveConfigRequest {
    config: AppConfig;
}

export interface RunDryRunRequest {
    runtime: RuntimeOptions;
}

export interface StartSessionRequest {
    numMessages: number;
    baseWaitSeconds: number;
    marginSeconds: number;
    token?: string;
}

export interface SessionControlRequest {
    action: 'pause' | 'resume' | 'stop';
    reason?: string;
}

export interface LoadLogsRequest {
    sessionId: string;
}

export interface OpenLogFileRequest {
    sessionId: string;
}

export interface SaveEnvironmentRequest {
    discordToken: string;
}

export interface SaveInboxMonitorSettingsRequest {
    settings: InboxMonitorSettings;
}

export interface StartInboxMonitorRequest {
    token?: string;
}

export interface SaveNotificationDeliverySettingsRequest {
    settings: NotificationDeliverySettings;
}

export interface SaveTelegramBotTokenRequest {
    botToken: string;
}

export type ConfigLoadResult =
    | { kind: 'ok'; config: AppConfig }
    | { kind: 'missing' }
    | { kind: 'invalid'; error: string }
;

export interface SaveConfigResult {
    ok: boolean;
    config: AppConfig;
}

export interface LogLoadResult {
    ok: boolean;
    path: string;
    entries: LogEntry[];
    warnings?: string[];
}

export interface ReleaseDiagnostics {
    appVersion: string;
    dataDir: string;
    logsDir: string;
    configPath: string;
    statePath: string;
    secureStorePath: string;
    tokenStorage: TokenStorageMode;
    sidecarStatus: SidecarStatus;
}

export interface SupportBundleResult {
    path: string;
    includedFiles: string[];
    missingFiles: string[];
}

export interface ResetRuntimeStateResult {
    ok: boolean;
    clearedStateFile: boolean;
    deletedLogFiles: number;
}

export type ChannelStatePhase = 'started' | 'stopped' | 'completed' | 'failed';

export type SessionUpdateReason = 'message_sent' | 'pacing_changed' | 'health_changed' | 'checkpoint_restored';

export type DesktopEvent =
    | { type: 'session_started'; state: SessionSnapshot }
    | { type: 'session_paused'; state: SessionSnapshot }
    | { type: 'session_resumed'; state: SessionSnapshot }
    | { type: 'session_stopping'; state: SessionSnapshot }
    | { type: 'channel_state_changed'; state: SessionSnapshot; channelId: string; phase: ChannelStatePhase }
    | { type: 'session_state_updated'; state: SessionSnapshot; reason: SessionUpdateReason }
    | { type: 'log_event_emitted'; entry: LogEntry }
    | { type: 'summary_ready'; summary: SessionSummary; state: SessionSnapshot }
    | { type: 'preflight_result_emitted'; result: PreflightResult }
    | { type: 'dry_run_ready'; result: DryRunResult }
    | { type: 'inbox_monitor_state_changed'; monitor: InboxMonitorState }
    | { type: 'inbox_notification_ready'; notification: InboxNotificationItem; monitor: InboxMonitorState }
    | { type: 'notification_delivery_state_changed'; delivery: NotificationDeliverySnapshot }
    | { type: 'telegram_test_result'; ok: boolean; message: string; state: TelegramState }
    | { type: 'telegram_chat_detected'; chatId: string; title?: string }
    | { type: 'close_blocked'; message: string; state: SessionSnapshot | null }
    | { type: 'sidecar_error'; message: string; status: 'restarting' | 'failed' }
    | { type: 'sidecar_ready' }
;

export type LogLevel = 'info' | 'success' | 'warning' | 'error' | 'debug';

export type SessionSegmentKind = 'fresh' | 'resumed';

export interface LogEntry {
    id: string;
    timestamp: string;
    level: LogLevel;
    context: string;
    message: string;
    meta?: Record<string, string | number | boolean | null>;
    sessionId?: string;
    segmentId?: string;
    segmentKind?: SessionSegmentKind;
}

export type InboxNotificationKind = 'direct_message' | 'message_request';

export type InboxMonitorStatus = 'stopped' | 'starting' | 'running' | 'blocked' | 'degraded' | 'failed';

export type TelegramDeliveryStatus = 'disabled' | 'unconfigured' | 'ready' | 'testing' | 'failed';

export type TelegramPreviewMode = 'full';

export interface InboxNotificationItem {
    id: string;
    kind: InboxNotificationKind;
    channelId: string;
    channelName: string;
    authorId: string;
    authorName: string;
    previewText: string;
    messageId: string;
    receivedAt: string;
}

export interface InboxMonitorSettings {
    enabled: boolean;
    pollIntervalSeconds: number;
    notifyDirectMessages: boolean;
    notifyMessageRequests: boolean;
}

export interface InboxMonitorState {
    status: InboxMonitorStatus;
    enabled: boolean;
    pollIntervalSeconds: number;
    lastCheckedAt?: string;
    lastSuccessfulPollAt?: string;
    lastNotificationAt?: string;
    lastError?: string;
    backoffUntil?: string;
}

export interface InboxMonitorLastSeen {
    initializedAt?: string;
    selfUserId?: string;
    channelMessageIds: Record<string, string>;
}

export interface InboxMonitorSnapshot {
    settings: InboxMonitorSettings;
    state: InboxMonitorState;
    lastSeen: InboxMonitorLastSeen;
}

export interface TelegramSettings {
    enabled: boolean;
    botTokenStored: boolean;
    chatId: string;
    previewMode: TelegramPreviewMode;
}

export interface TelegramState {
    status: TelegramDeliveryStatus;
    lastCheckedAt?: string;
    lastDeliveredAt?: string;
    lastTestedAt?: string;
    lastError?: string;
    lastResolvedChatTitle?: string;
}

export interface NotificationDeliverySettings {
    windowsDesktopEnabled: boolean;
    telegram: TelegramSettings;
}

export interface NotificationDeliverySnapshot {
    settings: NotificationDeliverySettings;
    telegramState: TelegramState;
}

export interface TelegramChatDetectionResult {
    chatId: string;
    title?: string;
}

export interface TelegramTestResult {
    ok: boolean;
    message: string;
    state: TelegramState;
}

export interface ChannelQuietHours {
    start: string;
    end: string;
}

export interface ChannelSchedule {
    intervalSeconds: number;
    randomMarginSeconds: number;
    quietHours?: ChannelQuietHours | null;
    timezone?: string | null;
    maxSendsPerDay?: number | null;
    cooldownWindowSize?: number;
}

export interface AppChannel {
    name: string;
    id: string;
    referrer: string;
    messageGroup: string;
    schedule?: ChannelSchedule;
}

export interface AppConfig {
    userAgent: string;
    channels: AppChannel[];
    messageGroups: Record<string, string[]>;
}

export interface RuntimeOptions {
    numMessages: number;
    baseWaitSeconds: number;
    marginSeconds: number;
}

export interface AdaptivePacingState {
    baseRequestIntervalMs: number;
    currentRequestIntervalMs: number;
    maxRequestIntervalMs: number;
    penaltyLevel: number;
    recentRateLimitCount: number;
    lastRateLimitAt?: string;
    lastRecoveryAt?: string;
}

export type ChannelHealthStatus = 'healthy' | 'degraded' | 'suppressed' | 'recovering' | 'failed';

export interface ChannelHealthRecord {
    channelId: string;
    channelName: string;
    status: ChannelHealthStatus;
    consecutiveRateLimits: number;
    consecutiveFailures: number;
    suppressionCount: number;
    lastReason?: string;
    lastFailureAt?: string;
    lastSuccessAt?: string;
    suppressedUntil?: string;
}

export type ChannelProgressStatus = 'pending' | 'running' | 'suppressed' | 'stopped' | 'completed' | 'failed';

export interface ChannelProgressRecord {
    channelId: string;
    channelName: string;
    status: ChannelProgressStatus;
    sentMessages: number;
    sentToday: number;
    sentTodayDayKey?: string;
    consecutiveRateLimits: number;
    lastMessage?: string;
    lastSentAt?: string;
    lastError?: string;
    suppressedUntil?: string;
}

export type SessionStatus = 'idle' | 'running' | 'paused' | 'stopping' | 'stopped' | 'completed' | 'failed';

export interface SessionChannelOutcome {
    channelId: string;
    channelName: string;
    status: 'completed' | 'failed' | 'suppressed';
    sentMessages: number;
    lastError?: string;
    suppressedUntil?: string;
}

export interface SessionSummary {
    totalChannels: number;
    completedChannels: number;
    failedChannels: number;
    sentMessages: number;
    startedAt: string;
    finishedAt?: string;
    stopReason?: string;
    rateLimitEvents?: number;
    suppressedChannels?: number;
    resumedFromCheckpoint?: boolean;
    maxPacingIntervalMs?: number;
    channelOutcomes?: SessionChannelOutcome[];
}

export interface SessionSnapshot {
    id: string;
    status: SessionStatus;
    startedAt?: string;
    updatedAt: string;
    currentSegmentId?: string;
    currentSegmentKind?: string;
    currentSegmentStartedAt?: string;
    resumedFromCheckpointAt?: string;
    activeChannels: string[];
    completedChannels: string[];
    failedChannels: string[];
    sentMessages: number;
    stopReason?: string;
    summary?: SessionSummary;
    runtime?: RuntimeOptions;
    channelProgress?: Record<string, ChannelProgressRecord>;
    channelHealth?: Record<string, ChannelHealthRecord>;
    pacing?: AdaptivePacingState;
    resumedFromCheckpoint?: boolean;
}

export interface ChannelPreflightResult {
    channelId: string;
    channelName: string;
    ok: boolean;
    skipped?: boolean;
    reason?: string;
    status?: number;
}

export interface PreflightResult {
    ok: boolean;
    checkedAt: string;
    configValid: boolean;
    tokenPresent: boolean;
    issues: string[];
    channels: ChannelPreflightResult[];
}

export interface DryRunCadence {
    numMessages: number;
    baseWaitSeconds: number;
    marginSeconds: number;
}

export interface DryRunChannelPreview {
    channelId: string;
    channelName: string;
    groupName: string;
    enabled: boolean;
    sampleMessages: string[];
    cadence: DryRunCadence;
    skipReasons: string[];
}

export interface DryRunSummary {
    selectedChannels: number;
    skippedChannels: number;
    totalSampleMessages: number;
}

export interface DryRunResult {
    generatedAt: string;
    willSendMessages: boolean;
    channels: DryRunChannelPreview[];
    summary: DryRunSummary;
}

export interface RecentFailure {
    channelId: string;
    channelName: string;
    reason: string;
    timestamp: string;
}

export interface ResumeSessionRecord {
    sessionId: string;
    updatedAt: string;
    runtime: RuntimeOptions;
    configSignature: string;
    state: SessionSnapshot;
    recentMessageHistory: Record<string, string[]>;
}

export interface SenderStateRecord {
    schemaVersion: number;
    lastSession?: SessionSnapshot;
    summaries: SessionSummary[];
    recentFailures: RecentFailure[];
    recentMessageHistory?: Record<string, string[]>;
    channelHealth?: Record<string, ChannelHealthRecord>;
    resumeSession?: ResumeSessionRecord;
    inboxMonitor?: InboxMonitorSnapshot;
    notificationDelivery?: NotificationDeliverySnapshot;
    warning?: string;
}

export type StateLoadResult = SenderStateRecord;

export type TokenStorageMode = 'secure' | 'missing';

export type SidecarStatus = 'connecting' | 'ready' | 'restarting' | 'failed';

export interface DesktopSetupState {
    tokenPresent: boolean;
    tokenStorage: TokenStorageMode;
    dataDir: string;
    secureStorePath: string;
    envPath: string;
    configPath: string;
    statePath: string;
    logsDir: string;
    warning?: string;
}

export interface DesktopCommandMap {
    load_config: {
        request: EmptyRequest;
        response: ConfigLoadResult;
    };
    save_config: {
        request: SaveConfigRequest;
        response: SaveConfigResult;
    };
    run_preflight: {
        request: RunPreflightRequest;
        response: PreflightResult;
    };
    run_dry_run: {
        request: RunDryRunRequest;
        response: DryRunResult;
    };
    start_session: {
        request: StartSessionRequest;
        response: SessionSnapshot;
    };
    pause_session: {
        request: EmptyRequest;
        response: SessionSnapshot | null;
    };
    resume_session: {
        request: EmptyRequest;
        response: SessionSnapshot | null;
    };
    stop_session: {
        request: EmptyRequest;
        response: SessionSnapshot | null;
    };
    get_session_state: {
        request: EmptyRequest;
        response: SessionSnapshot | null;
    };
    load_logs: {
        request: LoadLogsRequest;
        response: LogLoadResult;
    };
    load_state: {
        request: EmptyRequest;
        response: SenderStateRecord;
    };
    load_setup_state: {
        request: EmptyRequest;
        response: DesktopSetupState;
    };
    save_environment: {
        request: SaveEnvironmentRequest;
        response: DesktopSetupState;
    };
    clear_secure_token: {
        request: EmptyRequest;
        response: DesktopSetupState;
    };
    load_inbox_monitor_settings: {
        request: EmptyRequest;
        response: InboxMonitorSettings;
    };
    save_inbox_monitor_settings: {
        request: SaveInboxMonitorSettingsRequest;
        response: InboxMonitorSnapshot;
    };
    get_inbox_monitor_state: {
        request: EmptyRequest;
        response: InboxMonitorState;
    };
    start_inbox_monitor: {
        request: StartInboxMonitorRequest;
        response: InboxMonitorState;
    };
    stop_inbox_monitor: {
        request: EmptyRequest;
        response: InboxMonitorState;
    };
    load_notification_delivery_settings: {
        request: EmptyRequest;
        response: NotificationDeliverySettings;
    };
    save_notification_delivery_settings: {
        request: SaveNotificationDeliverySettingsRequest;
        response: NotificationDeliverySnapshot;
    };
    get_notification_delivery_state: {
        request: EmptyRequest;
        response: NotificationDeliverySnapshot;
    };
    save_telegram_bot_token: {
        request: SaveTelegramBotTokenRequest;
        response: NotificationDeliverySnapshot;
    };
    clear_telegram_bot_token: {
        request: EmptyRequest;
        response: NotificationDeliverySnapshot;
    };
    detect_telegram_chat: {
        request: EmptyRequest;
        response: TelegramChatDetectionResult;
    };
    send_test_telegram_notification: {
        request: EmptyRequest;
        response: TelegramTestResult;
    };
    discard_resume_session: {
        request: EmptyRequest;
        response: SenderStateRecord;
    };
    load_release_diagnostics: {
        request: EmptyRequest;
        response: ReleaseDiagnostics;
    };
    open_logs_directory: {
        request: EmptyRequest;
        response: string;
    };
    export_support_bundle: {
        request: EmptyRequest;
        response: SupportBundleResult;
    };
    reset_runtime_state: {
        request: EmptyRequest;
        response: ResetRuntimeStateResult;
    };
    open_log_file: {
        request: OpenLogFileRequest;
        response: string;
    };
    open_data_directory: {
        request: EmptyRequest;
        response: string;
    };
}

export type DesktopCommandName = keyof DesktopCommandMap;

export type SidecarCommandName = Exclude<
    DesktopCommandName,
    | 'open_log_file'
    | 'open_data_directory'
    | 'load_setup_state'
    | 'save_environment'
    | 'clear_secure_token'
    | 'load_notification_delivery_settings'
    | 'save_notification_delivery_settings'
    | 'get_notification_delivery_state'
    | 'save_telegram_bot_token'
    | 'clear_telegram_bot_token'
    | 'detect_telegram_chat'
    | 'send_test_telegram_notification'
    | 'load_release_diagnostics'
    | 'open_logs_directory'
    | 'export_support_bundle'
    | 'reset_runtime_state'
>;

export interface DesktopRpcRequest<K extends DesktopCommandName = DesktopCommandName> {
    id: string;
    command: K;
    payload: DesktopCommandMap[K]['request'];
}

export type DesktopRpcSuccessResponse<K extends DesktopCommandName = DesktopCommandName> = {
    type: 'response';
    id: string;
    ok: true;
    result: DesktopCommandMap[K]['response'];
};

export interface DesktopRpcErrorResponse {
    type: 'response';
    id: string;
    ok: false;
    error: string;
}

export type DesktopRpcResponse<K extends DesktopCommandName = DesktopCommandName> =
    | DesktopRpcSuccessResponse<K>
    | DesktopRpcErrorResponse;

export interface DesktopEventMessage {
    type: 'event';
    event: DesktopEvent;
}

export type DesktopSidecarMessage = DesktopRpcResponse | DesktopEventMessage;
