import fs from 'node:fs';
import path from 'node:path';

const repoRoot = process.cwd();

interface BudgetRule {
    label: string;
    maxLines: number;
    matches(filePath: string): boolean;
}

const budgetRules: BudgetRule[] = [
    {
        label: 'frontend controller/hook',
        maxLines: 200,
        matches: (filePath) => /^app\/src\/controllers\/desktop\/.+\.ts$/.test(filePath),
    },
    {
        label: 'frontend screen',
        maxLines: 250,
        matches: (filePath) => /^app\/src\/features\/.+-screen\.tsx$/.test(filePath),
    },
    {
        label: 'TypeScript application/infrastructure module',
        maxLines: 300,
        matches: (filePath) => /^src\/(application|infrastructure)\/.+\.ts$/.test(filePath),
    },
    {
        label: 'Rust module',
        maxLines: 350,
        matches: (filePath) => /^src-tauri\/src\/.+\.rs$/.test(filePath),
    },
];

function toRepoPath(filePath: string) {
    return path.relative(repoRoot, filePath).replace(/\\/g, '/');
}

function walk(directory: string, files: string[] = []) {
    for (const entry of fs.readdirSync(directory, { withFileTypes: true })) {
        const fullPath = path.join(directory, entry.name);
        if (entry.isDirectory()) {
            walk(fullPath, files);
            continue;
        }
        files.push(fullPath);
    }
    return files;
}

function isGenerated(contents: string) {
    return contents.startsWith('// Generated by scripts/generate-desktop-contracts.ts. Do not edit directly.');
}

function countBudgetLines(contents: string) {
    return contents
        .split(/\r?\n/)
        .map((line) => line.trim())
        .filter((line) => line.length > 0 && !line.startsWith('//')).length;
}

function isTestOrFixture(filePath: string) {
    return (
        /(^|\/)test\//.test(filePath) ||
        filePath.includes('.test.') ||
        filePath.endsWith('/src-tauri/src/tests.rs') ||
        filePath.endsWith('/src-tauri/src/tests/mod.rs')
    );
}

const files = [
    ...walk(path.join(repoRoot, 'app', 'src')),
    ...walk(path.join(repoRoot, 'src')),
    ...walk(path.join(repoRoot, 'src-tauri', 'src')),
];

const violations: string[] = [];

for (const absolutePath of files) {
    const repoPath = toRepoPath(absolutePath);
    const rule = budgetRules.find((candidate) => candidate.matches(repoPath));
    if (!rule) {
        continue;
    }

    if (isTestOrFixture(repoPath)) {
        continue;
    }

    const contents = fs.readFileSync(absolutePath, 'utf8');
    if (isGenerated(contents)) {
        continue;
    }

    const lineCount = countBudgetLines(contents);
    if (lineCount > rule.maxLines) {
        violations.push(
            `${repoPath} has ${lineCount} counted lines, above the ${rule.label} budget of ${rule.maxLines}.`,
        );
    }
}

if (violations.length > 0) {
    console.error('File-size budget violations found:');
    for (const violation of violations) {
        console.error(`- ${violation}`);
    }
    process.exit(1);
}

console.log('File-size budget check passed.');
