// Generated by scripts/generate-desktop-contracts.ts. Do not edit directly.
#![allow(dead_code)]

use std::collections::HashMap;
use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RunPreflightRequest {
    pub token: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SaveConfigRequest {
    pub config: AppConfig,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RunDryRunRequest {
    pub runtime: RuntimeOptions,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StartSessionRequest {
    pub num_messages: u32,
    pub base_wait_seconds: f64,
    pub margin_seconds: f64,
    pub token: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LoadLogsRequest {
    pub session_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OpenLogFileRequest {
    pub session_id: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SaveEnvironmentRequest {
    pub discord_token: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SaveInboxMonitorSettingsRequest {
    pub settings: InboxMonitorSettings,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct StartInboxMonitorRequest {
    pub token: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SaveNotificationDeliverySettingsRequest {
    pub settings: NotificationDeliverySettings,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SaveTelegramBotTokenRequest {
    pub bot_token: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum ConfigLoadResult {
    #[serde(rename = "ok")]
    Ok {
        config: AppConfig,
    },
    #[serde(rename = "missing")]
    Missing,
    #[serde(rename = "invalid")]
    Invalid {
        error: String,
    },
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SaveConfigResult {
    pub ok: bool,
    pub config: AppConfig,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LogLoadResult {
    pub ok: bool,
    pub path: String,
    pub entries: Vec<LogEntry>,
    pub warnings: Option<Vec<String>>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReleaseDiagnostics {
    pub app_version: String,
    pub data_dir: String,
    pub logs_dir: String,
    pub config_path: String,
    pub state_path: String,
    pub secure_store_path: String,
    pub token_storage: TokenStorageMode,
    pub sidecar_status: SidecarStatus,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SupportBundleResult {
    pub path: String,
    pub included_files: Vec<String>,
    pub missing_files: Vec<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResetRuntimeStateResult {
    pub ok: bool,
    pub cleared_state_file: bool,
    pub deleted_log_files: usize,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum LogLevel {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "debug")]
    Debug,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum SessionSegmentKind {
    #[serde(rename = "fresh")]
    Fresh,
    #[serde(rename = "resumed")]
    Resumed,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LogEntry {
    pub id: String,
    pub timestamp: String,
    pub level: LogLevel,
    pub context: String,
    pub message: String,
    pub meta: Option<HashMap<String, Value>>,
    pub session_id: Option<String>,
    pub segment_id: Option<String>,
    pub segment_kind: Option<SessionSegmentKind>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum InboxNotificationKind {
    #[serde(rename = "direct_message")]
    DirectMessage,
    #[serde(rename = "message_request")]
    MessageRequest,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum InboxMonitorStatus {
    #[serde(rename = "stopped")]
    Stopped,
    #[serde(rename = "starting")]
    Starting,
    #[serde(rename = "running")]
    Running,
    #[serde(rename = "blocked")]
    Blocked,
    #[serde(rename = "degraded")]
    Degraded,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum TelegramDeliveryStatus {
    #[serde(rename = "disabled")]
    Disabled,
    #[serde(rename = "unconfigured")]
    Unconfigured,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "testing")]
    Testing,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum TelegramPreviewMode {
    #[serde(rename = "full")]
    Full,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InboxNotificationItem {
    pub id: String,
    pub kind: InboxNotificationKind,
    pub channel_id: String,
    pub channel_name: String,
    pub author_id: String,
    pub author_name: String,
    pub preview_text: String,
    pub message_id: String,
    pub received_at: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InboxMonitorSettings {
    pub enabled: bool,
    pub poll_interval_seconds: u32,
    pub notify_direct_messages: bool,
    pub notify_message_requests: bool,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InboxMonitorState {
    pub status: InboxMonitorStatus,
    pub enabled: bool,
    pub poll_interval_seconds: u32,
    pub last_checked_at: Option<String>,
    pub last_successful_poll_at: Option<String>,
    pub last_notification_at: Option<String>,
    pub last_error: Option<String>,
    pub backoff_until: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InboxMonitorLastSeen {
    pub initialized_at: Option<String>,
    pub self_user_id: Option<String>,
    pub channel_message_ids: HashMap<String, String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InboxMonitorSnapshot {
    pub settings: InboxMonitorSettings,
    pub state: InboxMonitorState,
    pub last_seen: InboxMonitorLastSeen,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TelegramSettings {
    pub enabled: bool,
    pub bot_token_stored: bool,
    pub chat_id: String,
    pub preview_mode: TelegramPreviewMode,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TelegramState {
    pub status: TelegramDeliveryStatus,
    pub last_checked_at: Option<String>,
    pub last_delivered_at: Option<String>,
    pub last_tested_at: Option<String>,
    pub last_error: Option<String>,
    pub last_resolved_chat_title: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NotificationDeliverySettings {
    pub windows_desktop_enabled: bool,
    pub telegram: TelegramSettings,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct NotificationDeliverySnapshot {
    pub settings: NotificationDeliverySettings,
    pub telegram_state: TelegramState,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TelegramChatDetectionResult {
    pub chat_id: String,
    pub title: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TelegramTestResult {
    pub ok: bool,
    pub message: String,
    pub state: TelegramState,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelQuietHours {
    pub start: String,
    pub end: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelSchedule {
    pub interval_seconds: f64,
    pub random_margin_seconds: f64,
    pub quiet_hours: Option<ChannelQuietHours>,
    pub timezone: Option<String>,
    pub max_sends_per_day: Option<u32>,
    pub cooldown_window_size: Option<u32>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AppChannel {
    pub name: String,
    pub id: String,
    pub referrer: String,
    pub message_group: String,
    pub schedule: Option<ChannelSchedule>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AppConfig {
    pub user_agent: String,
    pub channels: Vec<AppChannel>,
    pub message_groups: HashMap<String, Vec<String>>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RuntimeOptions {
    pub num_messages: u32,
    pub base_wait_seconds: f64,
    pub margin_seconds: f64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AdaptivePacingState {
    pub base_request_interval_ms: u32,
    pub current_request_interval_ms: u32,
    pub max_request_interval_ms: u32,
    pub penalty_level: u32,
    pub recent_rate_limit_count: u32,
    pub last_rate_limit_at: Option<String>,
    pub last_recovery_at: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelHealthRecord {
    pub channel_id: String,
    pub channel_name: String,
    pub status: String,
    pub consecutive_rate_limits: u32,
    pub consecutive_failures: u32,
    pub suppression_count: u32,
    pub last_reason: Option<String>,
    pub last_failure_at: Option<String>,
    pub last_success_at: Option<String>,
    pub suppressed_until: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelProgressRecord {
    pub channel_id: String,
    pub channel_name: String,
    pub status: String,
    pub sent_messages: u32,
    pub sent_today: u32,
    pub sent_today_day_key: Option<String>,
    pub consecutive_rate_limits: u32,
    pub last_message: Option<String>,
    pub last_sent_at: Option<String>,
    pub last_error: Option<String>,
    pub suppressed_until: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionChannelOutcome {
    pub channel_id: String,
    pub channel_name: String,
    pub status: String,
    pub sent_messages: u32,
    pub last_error: Option<String>,
    pub suppressed_until: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionSummary {
    pub total_channels: usize,
    pub completed_channels: usize,
    pub failed_channels: usize,
    pub sent_messages: u32,
    pub started_at: String,
    pub finished_at: Option<String>,
    pub stop_reason: Option<String>,
    pub rate_limit_events: Option<u32>,
    pub suppressed_channels: Option<usize>,
    pub resumed_from_checkpoint: Option<bool>,
    pub max_pacing_interval_ms: Option<u32>,
    pub channel_outcomes: Option<Vec<SessionChannelOutcome>>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionSnapshot {
    pub id: String,
    pub status: String,
    pub started_at: Option<String>,
    pub updated_at: String,
    pub current_segment_id: Option<String>,
    pub current_segment_kind: Option<String>,
    pub current_segment_started_at: Option<String>,
    pub resumed_from_checkpoint_at: Option<String>,
    pub active_channels: Vec<String>,
    pub completed_channels: Vec<String>,
    pub failed_channels: Vec<String>,
    pub sent_messages: u32,
    pub stop_reason: Option<String>,
    pub summary: Option<SessionSummary>,
    pub runtime: Option<RuntimeOptions>,
    pub channel_progress: Option<HashMap<String, ChannelProgressRecord>>,
    pub channel_health: Option<HashMap<String, ChannelHealthRecord>>,
    pub pacing: Option<AdaptivePacingState>,
    pub resumed_from_checkpoint: Option<bool>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannelPreflightResult {
    pub channel_id: String,
    pub channel_name: String,
    pub ok: bool,
    pub skipped: Option<bool>,
    pub reason: Option<String>,
    pub status: Option<u16>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PreflightResult {
    pub ok: bool,
    pub checked_at: String,
    pub config_valid: bool,
    pub token_present: bool,
    pub issues: Vec<String>,
    pub channels: Vec<ChannelPreflightResult>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DryRunCadence {
    pub num_messages: u32,
    pub base_wait_seconds: f64,
    pub margin_seconds: f64,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DryRunChannelPreview {
    pub channel_id: String,
    pub channel_name: String,
    pub group_name: String,
    pub enabled: bool,
    pub sample_messages: Vec<String>,
    pub cadence: DryRunCadence,
    pub skip_reasons: Vec<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DryRunSummary {
    pub selected_channels: u32,
    pub skipped_channels: u32,
    pub total_sample_messages: u32,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DryRunResult {
    pub generated_at: String,
    pub will_send_messages: bool,
    pub channels: Vec<DryRunChannelPreview>,
    pub summary: DryRunSummary,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RecentFailure {
    pub channel_id: String,
    pub channel_name: String,
    pub reason: String,
    pub timestamp: String,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ResumeSessionRecord {
    pub session_id: String,
    pub updated_at: String,
    pub runtime: RuntimeOptions,
    pub config_signature: String,
    pub state: SessionSnapshot,
    pub recent_message_history: HashMap<String, Vec<String>>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SenderStateRecord {
    pub schema_version: u32,
    pub last_session: Option<SessionSnapshot>,
    pub summaries: Vec<SessionSummary>,
    pub recent_failures: Vec<RecentFailure>,
    pub recent_message_history: Option<HashMap<String, Vec<String>>>,
    pub channel_health: Option<HashMap<String, ChannelHealthRecord>>,
    pub resume_session: Option<ResumeSessionRecord>,
    pub inbox_monitor: Option<InboxMonitorSnapshot>,
    pub notification_delivery: Option<NotificationDeliverySnapshot>,
    pub warning: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum TokenStorageMode {
    #[serde(rename = "secure")]
    Secure,
    #[serde(rename = "missing")]
    Missing,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum SidecarStatus {
    #[serde(rename = "connecting")]
    Connecting,
    #[serde(rename = "ready")]
    Ready,
    #[serde(rename = "restarting")]
    Restarting,
    #[serde(rename = "failed")]
    Failed,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DesktopSetupState {
    pub token_present: bool,
    pub token_storage: TokenStorageMode,
    pub data_dir: String,
    pub secure_store_path: String,
    pub env_path: String,
    pub config_path: String,
    pub state_path: String,
    pub logs_dir: String,
    pub warning: Option<String>,
}
